# Generated by Django 4.2.3 on 2023-07-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clovia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.EmailField(help_text='Enter Your Email Address', max_length=100),
        ),
    ]
