# Generated by Django 4.2.3 on 2023-07-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clovia', '0002_alter_login_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting_Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.EmailField(max_length=100),
        ),
    ]
