# Generated by Django 4.2.3 on 2023-07-28 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clovia', '0003_meeting_rooms_alter_login_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Booking At')),
                ('booking_duration', models.DurationField(verbose_name='Duration')),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clovia.meeting_rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clovia.login')),
            ],
        ),
    ]
