# Generated by Django 4.2.3 on 2023-07-28 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clovia', '0004_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Booking At'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_date',
            field=models.DateField(verbose_name='Booking On'),
        ),
    ]
