# Generated by Django 4.2.3 on 2023-07-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clovia', '0005_bookings_booking_time_alter_bookings_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='room_name',
        ),
        migrations.AddField(
            model_name='meeting_rooms',
            name='bookings',
            field=models.ManyToManyField(related_name='meeting_rooms', to='clovia.bookings'),
        ),
    ]
