# Generated by Django 4.2.3 on 2023-07-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clovia', '0008_remove_bookings_meeting_rooms_bookings_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
