# Generated by Django 4.2.3 on 2023-07-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clovia', '0009_alter_login_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.EmailField(max_length=100),
        ),
    ]
