# Generated by Django 4.2.3 on 2023-07-31 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clovia', '0010_alter_login_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='participant',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Participants'),
        ),
    ]
