# Generated by Django 4.2.3 on 2023-07-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clovia', '0012_remove_bookings_participant_bookings_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_duration',
            field=models.TimeField(verbose_name='Duration'),
        ),
    ]
