# Generated by Django 4.2.3 on 2023-08-02 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clovia', '0013_alter_bookings_booking_duration'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='bookings',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Ends At'),
            preserve_default=False,
        ),
    ]
