# Generated by Django 4.2.3 on 2023-08-03 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clovia', '0016_remove_bookings_booking_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='participants',
            field=models.ManyToManyField(related_name='bookings_participated', to='clovia.login'),
        ),
    ]
