# Generated by Django 4.2.3 on 2023-08-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clovia', '0017_alter_bookings_participants'),
        ('clovia', '0018_notification'),
    ]

    operations = [
    ]
