# Generated by Django 4.2.3 on 2023-08-12 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clovia', '0018_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
