# Generated by Django 4.2.3 on 2023-08-12 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clovia', '0019_merge_20230805_1800'),
        ('clovia', '0020_bookings_google_calendar_event_id'),
    ]

    operations = [
    ]
