# Generated by Django 4.2.3 on 2023-08-02 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting_Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='Booking On')),
                ('booking_time', models.TimeField(verbose_name='Booking At')),
                ('end_time', models.TimeField(verbose_name='Ends At')),
                ('participants', models.ManyToManyField(blank=True, related_name='bookings_participated', to='demo.login')),
                ('room_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.meeting_rooms')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.login')),
            ],
        ),
    ]
